eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
server:
  port: 8001
sidecar:
  health-uri: http://localhost:${sidecar.port}/health
  port: 3000
spring:
  application:
    name: py-sidecar
logging:
  file: /logs/${spring.application.name}.log
  level:
    root: info