eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
server:
  port: 8761
spring:
  application:
    name: registry
logging:
  file: /logs/${spring.application.name}.log
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: "*"