version: '2'
services:
  py-sidecar:
    image: rlsoms-py-sidecar
    volumes:
      - ./tmp:/tmp
    environment:
      - PYTHONUNBUFFERED = 0
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://rlsoms-registry:8761/eureka
    ports:
      - 8001:8001
      - 3000:3000
